# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in_calss_teacher_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.setWindowIcon(QIcon('image/ICO.ico'))
        Dialog.resize(657, 355)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 471, 331))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.signinTable = QtWidgets.QTableView(self.groupBox)
        self.signinTable.setGeometry(QtCore.QRect(20, 60, 431, 251))
        self.signinTable.setObjectName("signinTable")
        self.show_timeLable = QtWidgets.QLabel(Dialog)
        self.show_timeLable.setGeometry(QtCore.QRect(490, 60, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.show_timeLable.setFont(font)
        self.show_timeLable.setObjectName("show_timeLable")
        self.endClassBtn = QtWidgets.QPushButton(Dialog)
        self.endClassBtn.setGeometry(QtCore.QRect(500, 230, 121, 61))
        self.endClassBtn.setObjectName("endClassBtn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(510, 150, 72, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sumLable = QtWidgets.QLabel(Dialog)
        self.sumLable.setGeometry(QtCore.QRect(550, 180, 72, 15))
        self.sumLable.setObjectName("sumLable")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "课堂"))
        self.groupBox.setTitle(_translate("Dialog", "讲课中·"))
        self.label.setText(_translate("Dialog", "到课学生"))
        self.show_timeLable.setDisabled(True)
        self.show_timeLable.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#0055ff;\">00:45:00</span></p></body></html>"))
        self.endClassBtn.setText(_translate("Dialog", "下课"))
        self.label_3.setText(_translate("Dialog", "到课人数："))
        self.sumLable.setText(_translate("Dialog", "30人"))
