# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'at_class_students.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_inClass(object):
    def setupUi(self, inClass):
        inClass.setObjectName("inClass")
        self.setWindowIcon(QIcon('image/ICO.ico'))
        inClass.resize(648, 393)
        self.centralwidget = QtWidgets.QWidget(inClass)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 621, 331))
        self.groupBox.setObjectName("groupBox")
        self.videoDisplay = QtWidgets.QLabel(self.groupBox)
        self.videoDisplay.setGeometry(QtCore.QRect(20, 30, 371, 281))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.videoDisplay.setFont(font)
        self.videoDisplay.setStyleSheet("")
        self.videoDisplay.setText("")
        self.videoDisplay.setFixedSize(361,321)
        self.videoDisplay.setPixmap(QtGui.QPixmap("image/enter_class.png"))
        self.videoDisplay.setScaledContents(True)
        self.videoDisplay.setObjectName("videoDisplay")
        self.videoDisplay.lower()
        self.levelLable = QtWidgets.QLabel(self.groupBox)
        self.levelLable.setGeometry(QtCore.QRect(520, 60, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.levelLable.setFont(font)
        self.levelLable.setObjectName("levelLable")
        self.timeLable = QtWidgets.QLabel(self.groupBox)
        self.timeLable.setGeometry(QtCore.QRect(500, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.timeLable.setFont(font)
        self.timeLable.setObjectName("timeLable")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        self.cameraBtn = QtWidgets.QPushButton(self.groupBox)
        self.cameraBtn.setGeometry(QtCore.QRect(460, 170, 141, 41))
        self.cameraBtn.setObjectName("cameraBtn")
        self.exitBtn = QtWidgets.QPushButton(self.groupBox)
        self.exitBtn.setGeometry(QtCore.QRect(460, 260, 141, 41))
        self.exitBtn.setObjectName("exitBtn")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(410, 80, 72, 15))
        self.label_3.setObjectName("label_3")
        inClass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(inClass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 26))
        self.menubar.setObjectName("menubar")
        inClass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(inClass)
        self.statusbar.setObjectName("statusbar")
        inClass.setStatusBar(self.statusbar)

        self.retranslateUi(inClass)
        QtCore.QMetaObject.connectSlotsByName(inClass)

    def retranslateUi(self, inClass):
        _translate = QtCore.QCoreApplication.translate
        inClass.setWindowTitle(_translate("inClass", "-课堂-"))
        self.groupBox.setTitle(_translate("inClass", "上课中·"))
        self.levelLable.setText(_translate("inClass", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#55aaff;\">A</span></p></body></html>"))
        self.timeLable.setText(_translate("inClass", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#5500ff;\">00:45:00</span></p></body></html>"))
        self.label_2.setText(_translate("inClass", "课堂计时"))
        self.cameraBtn.setText(_translate("inClass", "开启摄像头"))
        self.exitBtn.setText(_translate("inClass", "退出课堂"))
        self.label_3.setText(_translate("inClass", "当前评价"))
