# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName('login')
        Dialog.setWindowTitle('登录')
        self.setWindowIcon(QIcon('image/ICO.ico'))
        Dialog.resize(404, 362)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 351))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(260, 40, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 240, 72, 15))
        self.label_3.setObjectName("label_3")
        self.accoutEdit = QtWidgets.QLineEdit(self.groupBox)
        self.accoutEdit.setGeometry(QtCore.QRect(100, 180, 161, 31))
        self.accoutEdit.setObjectName("accoutEdit")
        self.pswdEdit = QtWidgets.QLineEdit(self.groupBox)
        self.pswdEdit.setGeometry(QtCore.QRect(100, 230, 161, 31))
        self.pswdEdit.setObjectName("pswdEdit")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(260, 70, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.loginBtn = QtWidgets.QPushButton(self.groupBox)
        self.loginBtn.setGeometry(QtCore.QRect(120, 280, 131, 31))
        self.loginBtn.setObjectName("loginBtn")
        self.registBtn = QtWidgets.QPushButton(self.groupBox)
        self.registBtn.setGeometry(QtCore.QRect(290, 180, 71, 31))
        self.registBtn.setObjectName("registBtn")
        self.head = QtWidgets.QLabel(self.groupBox)
        self.head.setGeometry(QtCore.QRect(110, 40, 121, 111))
        self.head.setObjectName("head")
        pix = QPixmap('image/student_head.png')
        self.head.setPixmap(pix)
        self.head.setScaledContents(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "用户登录"))
        self.groupBox.setTitle(_translate("Dialog", "登录"))
        self.label.setText(_translate("Dialog", "切换身份"))
        self.label_2.setText(_translate("Dialog", "账号"))
        self.label_3.setText(_translate("Dialog", "密码"))
        self.comboBox.setItemText(0, _translate("Dialog", "学生"))
        self.comboBox.setItemText(1, _translate("Dialog", "老师"))
        self.loginBtn.setText(_translate("Dialog", "登录"))
        self.registBtn.setText(_translate("Dialog", "注册"))
