# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_students_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.setWindowIcon(QIcon('image/ICO.ico'))
        MainWindow.resize(762, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 711, 261))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.classTable = QtWidgets.QTableView(self.groupBox_2)
        self.classTable.setGeometry(QtCore.QRect(20, 30, 501, 201))
        self.classTable.setObjectName("classTable")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(540, 50, 151, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.newRoomBtn = QtWidgets.QPushButton(self.groupBox)
        self.newRoomBtn.setGeometry(QtCore.QRect(20, 40, 111, 41))
        self.newRoomBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.newRoomBtn.setObjectName("newRoomBtn")
        self.enterRoomBtn = QtWidgets.QPushButton(self.groupBox)
        self.enterRoomBtn.setGeometry(QtCore.QRect(20, 100, 111, 41))
        self.enterRoomBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterRoomBtn.setObjectName("enterRoomBtn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 711, 231))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.reportsTable = QtWidgets.QTableView(self.groupBox_3)
        self.reportsTable.setGeometry(QtCore.QRect(20, 40, 501, 161))
        self.reportsTable.setObjectName("reportsTable")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(540, 40, 151, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.detailBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.detailBtn.setGeometry(QtCore.QRect(20, 30, 111, 41))
        self.detailBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.detailBtn.setObjectName("detailBtn")
        self.outputBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.outputBtn.setGeometry(QtCore.QRect(20, 90, 111, 41))
        self.outputBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.outputBtn.setObjectName("outputBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "我学的课"))
        self.groupBox.setTitle(_translate("MainWindow", "管理课程"))
        self.newRoomBtn.setText(_translate("MainWindow", "开始自习"))
        self.enterRoomBtn.setText(_translate("MainWindow", "进入课堂"))
        self.groupBox_3.setTitle(_translate("MainWindow", "历史课堂记录"))
        self.groupBox_4.setTitle(_translate("MainWindow", "历史信息"))
        self.detailBtn.setText(_translate("MainWindow", "查看详情"))
        self.outputBtn.setText(_translate("MainWindow", "导出数据"))
