# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(764, 462)
        self.classTable = QtWidgets.QTableView(Dialog)
        self.classTable.setGeometry(QtCore.QRect(50, 80, 521, 331))
        self.classTable.setObjectName("classTable")
        self.classID_Edit = QtWidgets.QLineEdit(Dialog)
        self.classID_Edit.setGeometry(QtCore.QRect(170, 30, 121, 21))
        self.classID_Edit.setObjectName("classID_Edit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.outputBtn = QtWidgets.QPushButton(Dialog)
        self.outputBtn.setGeometry(QtCore.QRect(610, 310, 111, 51))
        self.outputBtn.setObjectName("outputBtn")
        self.clearBtn = QtWidgets.QPushButton(Dialog)
        self.clearBtn.setGeometry(QtCore.QRect(610, 210, 111, 51))
        self.clearBtn.setObjectName("clearBtn")
        self.queryBtn = QtWidgets.QPushButton(Dialog)
        self.queryBtn.setGeometry(QtCore.QRect(610, 120, 111, 51))
        self.queryBtn.setObjectName("queryBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "查询"))
        self.label_2.setText(_translate("Dialog", "课堂码"))
        self.outputBtn.setText(_translate("Dialog", "导出"))
        self.clearBtn.setText(_translate("Dialog", "清空"))
        self.queryBtn.setText(_translate("Dialog", "查询"))
