# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(728, 389)
        self.classTable = QtWidgets.QTableView(Dialog)
        self.classTable.setGeometry(QtCore.QRect(30, 30, 521, 331))
        self.classTable.setObjectName("classTable")
        self.outputBtn = QtWidgets.QPushButton(Dialog)
        self.outputBtn.setGeometry(QtCore.QRect(590, 260, 111, 51))
        self.outputBtn.setObjectName("outputBtn")
        self.clearBtn = QtWidgets.QPushButton(Dialog)
        self.clearBtn.setGeometry(QtCore.QRect(590, 160, 111, 51))
        self.clearBtn.setObjectName("clearBtn")
        self.queryBtn = QtWidgets.QPushButton(Dialog)
        self.queryBtn.setGeometry(QtCore.QRect(590, 70, 111, 51))
        self.queryBtn.setObjectName("queryBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "查询"))
        self.outputBtn.setText(_translate("Dialog", "导出"))
        self.clearBtn.setText(_translate("Dialog", "清空"))
        self.queryBtn.setText(_translate("Dialog", "查询"))
